// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vsudnoizpaeeaqhyovrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzdWRub2l6cGFlZWFxaHlvdnJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3MjkwODAsImV4cCI6MjA4ODMwNTA4MH0.kXyowWxvvs1-xBNEYFUXFh_you4LPWiLk68tKZYS9Pk";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);